name: Deploy to BETA and run script

on:
    pull_request:
        branches: ['main']

jobs:
    deploy_resources:
        runs-on: ubuntu-latest
        steps: 
            - name: AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region:             ${{ secrets.AWS_REGION }}

            - uses: actions/checkout@v5

            - name: Deploy CFN Stack
              run: |
                aws cloudformation deploy \
                  --stack-name {{ secrets.CFN_STACK_NAME }} \
                  --template-file infrastructure/cloudformation/deploy_S3_and_DynamoDB.yml \
                  --capabilities CAPABILITY_NAMED_IAM \
                  --parameter-overrides \
                    BucketName=${{ secrets.S3_BUCKET }}
                    BucketKey=${{ secrets.S3_BUCKET_KEY}}
                    DynamoDBDeploymentTrackingTableName=${{ secrets.DYNAMO_DB_TABLE_DEPLOYMENT_TRACKING }}
                    DynamoDBResumeAnalyticsTableName=${{ secrets.DYNAMO_DB_TABLE_RESUME_ANALYTICS }}